"""empty message

Revision ID: 132cb1bf5d86
Revises: 
Create Date: 2025-02-28 12:27:21.953946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132cb1bf5d86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('session', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
