"""fixing

Revision ID: 262d2f46747a
Revises: 92513edcd679
Create Date: 2025-02-27 17:06:42.876528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '262d2f46747a'
down_revision = '92513edcd679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('content',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
