"""Added is_admin

Revision ID: e16fe7e8312a
Revises: 
Create Date: 2025-02-27 15:39:14.543695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e16fe7e8312a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.String(length=10), nullable=False))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.String(length=12),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('sub_heading',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('sub_heading',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=12),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('is_admin')

    op.create_table('user',
    sa.Column('sno', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('date', mysql.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('sno'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
