"""content conversion to text

Revision ID: e21ea788a0de
Revises: 3169ce50337a
Create Date: 2025-02-27 16:54:08.284215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e21ea788a0de'
down_revision = '3169ce50337a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=mysql.TIMESTAMP(fsp=6),
               type_=sa.String(length=12),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp(6)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=12),
               type_=mysql.TIMESTAMP(fsp=6),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp(6)'))
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
